spring:
  application:
    name: eureka-service

server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8080/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0
    
  instance:
    prefer-ip-address: true


logging:
    file: eureka-service.log
zuul:
  #Service will be mapped under the /api URI
  prefix: /account
  routes:
    account-service:
      path: /**
      url: http://localhost:8081/
    transaction-service:
      path: /**
      url: http://localhost:8083/
    
